Add rule for plugins without required
efabrica-team/phpstan-rules pull request #14
Opened 2022-09-02 13:56 UTC by romanmatyus

2022-09-02 18:01 UTC, lulco commented
Is it working without some source files of notcms/core? Some stubs

2022-09-02 18:02 UTC, lulco requested changes

2022-09-02 18:02 UTC, lulco commented on CHANGELOG.md
> +- Rule for checking call `setRequired()` in method `globalConfiguration` - for Notcms plugins
Should be pageConfiguration, not globalConfiguration

2022-09-02 18:02 UTC, lulco commented on src/Rule/Notcms/PluginConfigItemNoRequiredInGlobalConfigurationRule.php
> +        if ($scope->getFunctionName() !== 'globalConfiguration') {
Page

2022-09-02 18:02 UTC, lulco commented on src/Rule/Notcms/PluginConfigItemNoRequiredInGlobalConfigurationRule.php
> +        if ($node->name->name !== 'setRequired') {
We need to test caller too. There can be setRequire() call also on non-ConfigItems

2022-09-02 18:02 UTC, lulco commented on src/Rule/Notcms/PluginConfigItemNoRequiredInGlobalConfigurationRule.php
> +        if (get_class($node) !== MethodCall::class) {
Instanceof would be better

2022-09-02 18:02 UTC, lulco commented on src/Rule/Notcms/PluginConfigItemNoRequiredInGlobalConfigurationRule.php
> +        if (!$scope->isInClass()) {
Maybe we should check if it is in class of type PluginDefinition

2022-09-02 18:52 UTC, romanmatyus commented
Can I add some stub files from Notcms? License etc..?

2022-09-04 20:28 UTC, lulco commented
> @lulco Can I add some stub files from Notcms? License etc..?

It would be better to create rule more generic - in class, in method, caller class and called method name should be in parameters and the rule would be registered in final config

2022-09-04 20:28 UTC, lulco commented
Also, please add new rule to readme

2022-09-05 11:57 UTC, romanmatyus commented on src/Rule/Notcms/PluginConfigItemNoRequiredInGlobalConfigurationRule.php
> +        if (!$scope->isInClass()) {
It's possible only with load real package. Stub files not support reflection for this.

2022-09-06 07:44 UTC, lulco commented on CHANGELOG.md
> +- Rule for checking call `setRequired()` in method `globalConfiguration` - for Notcms plugins
rule for check calling method in object method

2022-09-06 07:44 UTC, lulco commented on README.md
> +        factory: Efabrica\PHPStanRules\Rule\General\DisableCallMethodInObjectMethodRule('pageConfiguration', 'setRequired')
I miss some other context: context class, context method, caller class, called method. You have just context method and called method. I am not sure if it is enough

2022-09-06 07:44 UTC, lulco commented on composer.json
> +        "tracy/tracy": "*",
we don't need tracy here

2022-09-06 07:44 UTC, lulco commented on rules.neon
> +	stubFiles:
use spaces

2022-09-06 07:44 UTC, lulco commented on src/Rule/General/DisableCallMethodInObjectMethodRule.php
> +        $errors[] = RuleErrorBuilder::message('Method ' . $scope->getClassReflection()->getName() . '::' . $scope->getFunctionName() . ' is called with ' . $node->name->name . '() option.')->file($fi
is called with option is little bit wrong, you should tell user that he uses method in context of class / method

2022-09-06 07:44 UTC, lulco commented on src/stubs/BasePluginDefinition.stub
> +abstract class BasePluginDefinition implements PluginDefinitionInterface
no need to use whole class, just some sampe methods

2022-09-06 07:44 UTC, lulco commented on tests/Rule/General/DisableCallMethodInObjectMethodRule/Fixtures/PluginWithSetRequired.php
> +            new ChoozerConfigItem('main_menu_parent_page_id', 'Stránka s hlavným menu', 'page'),
english please

2022-10-07 23:48 UTC, mabar commented on src/stubs/BasePluginDefinition.stub
> +abstract class BasePluginDefinition implements PluginDefinitionInterface
Oh man, don't you have headaches from such classes? :'D

2022-10-08 07:04 UTC, lulco commented on src/stubs/BasePluginDefinition.stub
> +abstract class BasePluginDefinition implements PluginDefinitionInterface
Not at all :)

2022-11-04 17:24 UTC, merged

2022-11-04 17:24 UTC, lulco commented
Thanks I'll finish some cleanup later